//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 01:07:13 PM EET 
//


package com.medicalplatformp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activitiesDuration" type="{http://www.medicalPlatformP.com}durationList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activitiesDuration"
})
@XmlRootElement(name = "activityResponse")
public class ActivityResponse {

    @XmlElement(required = true)
    protected DurationList activitiesDuration;

    /**
     * Gets the value of the activitiesDuration property.
     * 
     * @return
     *     possible object is
     *     {@link DurationList }
     *     
     */
    public DurationList getActivitiesDuration() {
        return activitiesDuration;
    }

    /**
     * Sets the value of the activitiesDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationList }
     *     
     */
    public void setActivitiesDuration(DurationList value) {
        this.activitiesDuration = value;
    }

}
