//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 01:07:13 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.medicalPlatformP.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.medicalplatformp;
