//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 07:05:55 PM EET 
//


package soapServices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soapServices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soapServices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivityRequest }
     * 
     */
    public ActivityRequest createActivityRequest() {
        return new ActivityRequest();
    }

    /**
     * Create an instance of {@link RecommendationRequest }
     * 
     */
    public RecommendationRequest createRecommendationRequest() {
        return new RecommendationRequest();
    }

    /**
     * Create an instance of {@link MedicationRequest }
     * 
     */
    public MedicationRequest createMedicationRequest() {
        return new MedicationRequest();
    }

    /**
     * Create an instance of {@link ActivityResponse }
     * 
     */
    public ActivityResponse createActivityResponse() {
        return new ActivityResponse();
    }

    /**
     * Create an instance of {@link DurationList }
     * 
     */
    public DurationList createDurationList() {
        return new DurationList();
    }

    /**
     * Create an instance of {@link RecommendationResponse }
     * 
     */
    public RecommendationResponse createRecommendationResponse() {
        return new RecommendationResponse();
    }

    /**
     * Create an instance of {@link MedicationResponse }
     * 
     */
    public MedicationResponse createMedicationResponse() {
        return new MedicationResponse();
    }

    /**
     * Create an instance of {@link DurationObject }
     * 
     */
    public DurationObject createDurationObject() {
        return new DurationObject();
    }

}
